### ISSUE TITLE
Take semver seriously

### ISSUE THREAD

**Issue by Gnimuc** [JuliaImGui/cimgui-pack#2]
x-ref: https://github.com/Gnimuc/CImGui.jl/issues/88

we should have tagged 0.1.3 as 0.2.0 because it introduces breaking changes...

@JamesWrigley

**Comment by JamesWrigley** [comment]
Oops, you're quite right :facepalm:

**Comment by sairus7** [comment]
To the list of problems associated with semver, we should probably use ~ for LibCImGui versions across backends: https://github.com/JuliaImGui/ImGuiGLFWBackend.jl and https://github.com/JuliaImGui/ImGuiOpenGLBackend.jl

see https://github.com/JuliaImGui/ImGuiOpenGLBackend.jl/issues/5

**Comment by Gnimuc** [comment]
I tagged the lastest master as v0.2.0.
